name: tdiwef_logging
version: 1.1.0

description: >-
  Fork from package logging-1.0.2. Changed logging levels to tfiwer style
  Provides APIs for debugging and error logging, similar to loggers in other
  languages, such as the NodeJS.
repository: https://github.com/gbublik/tdiwef-logging

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
